---
title: "QFISH_NetFishery_Data"
author: "Ramaa Shenoy"
format: html
date: "2024-09-09"
---

# STEP-1: Installing and loading packages
```{r}
#install.packages("usethis")
#install.packages("tidyverse")
#install.packages("readr")
library(readr)
library(tidyverse)
library(ggplot2)
```

# STEP-2: Committing the project to my GitHub repository
```{r}
library("usethis")
usethis::use_github()
```

#Dataset can be downloaded from: https://qfish.fisheries.qld.gov.au/query/commercial-net-fishery/table

# STEP-3: Loading the dataset:
```{r}
getwd()
export <-
read_csv("data/export.csv") 
```
#Note to self: Adding data in line 27 adds the specified folder in where the dataset has been stored in R

#STEP-4: Reading the data:
```{r}
view(export)
```

#STEP-5: Creating the ggplot:
```{r}
ggplot(data = export, aes(x = as.numeric(CalendarYear)) ) +
  geom_line(aes(y = Tonnes, color = "grey"), size = 1) +  # Line for Tonnes of fish caught
  geom_point(aes(y = Tonnes, color = "Tonnes"), size = 2) +  # Points for Tonnes of fish caught
  geom_line(aes(y = Days, color = "grey"), size = 1) +  # Line for Fishing Effort (Days) 
  geom_point(aes(y = Days, color = "Days"), size = 2) +  # Points for Fishing Effort (Days)
  labs(title = "Annual Trends in Net Fishery Catch (1990–Present)",
       x = "Calendar Year",
       y = "Fish Caught in Tonnes") +
  scale_x_continuous(breaks = seq(1990, max(as.numeric(export$CalendarYear)), by = 4)) +  # 4-year intervals on X-axis
  scale_y_continuous(name = "Fish Caught in Tonnes", 
                     sec.axis = sec_axis(~., name = "Fishing Effort (Days)")) +  # Secondary axis for Fishing Effort (Days)
  scale_color_manual(values = c("Tonnes" = "blue", "Days" = "green"), 
                     labels = c("Tonnes" = "Tonnes of Fish Caught", "Days" = "Fishing Effort (Days)")) +  # Assigning colors to legend entries
  theme_minimal() +
  theme(panel.grid.major = element_blank(),  # Remove major gridlines
        panel.grid.minor = element_blank(),  # Remove minor gridlines
        axis.line = element_line(color = "black"))+  # Set axis lines to black  
guides(color = guide_legend(title = "Legend"))  # Setting the legend title to "Legend"
```
